"""Add custom_bg_image field for profile background images

Revision ID: 5c5339a0bd05
Revises: 5f2d8a484695
Create Date: 2025-12-21 13:23:12.467842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5339a0bd05'
down_revision: Union[str, Sequence[str], None] = '5f2d8a484695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with error handling to skip if it already exists
    try:
        op.add_column('users', sa.Column('custom_bg_image', sa.String(length=255), nullable=True))
    except:
        pass  # Column already exists, skip


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_bg_image')
    # ### end Alembic commands ###
