"""Add social media fields youtube twitch linkedin instagram discord tiktok to users

Revision ID: 5f2d8a484695
Revises: b0ad47f830c7
Create Date: 2025-12-21 13:18:48.252322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2d8a484695'
down_revision: Union[str, Sequence[str], None] = 'b0ad47f830c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with error handling to skip if they already exist
    columns_to_add = [
        ('youtube', sa.Column('youtube', sa.String(length=100), nullable=True)),
        ('twitch', sa.Column('twitch', sa.String(length=100), nullable=True)),
        ('linkedin', sa.Column('linkedin', sa.String(length=100), nullable=True)),
        ('instagram', sa.Column('instagram', sa.String(length=100), nullable=True)),
        ('discord', sa.Column('discord', sa.String(length=100), nullable=True)),
        ('tiktok', sa.Column('tiktok', sa.String(length=100), nullable=True)),
    ]
    
    for col_name, col_def in columns_to_add:
        try:
            op.add_column('users', col_def)
        except:
            pass  # Column already exists, skip


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tiktok')
    op.drop_column('users', 'discord')
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'twitch')
    op.drop_column('users', 'youtube')
    # ### end Alembic commands ###
