"""Add SiteSettings table for admin customization

Revision ID: ae7eec2f994b
Revises: 5c5339a0bd05
Create Date: 2025-12-21 13:28:52.033699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7eec2f994b'
down_revision: Union[str, Sequence[str], None] = '5c5339a0bd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
